name: nft_marketplace
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter_screenutil:
  flutter_svg:
  iconsax:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

fonts:
  - family: Dsignes
    fonts:
      - asset: assets/fonts/DsignesR.ttf
      - asset: assets/fonts/DsignesL.ttf
        weight: 200
      - asset: assets/fonts/DsignesB.ttf
        weight: 600
